001_src/MedicalStoreManagement/MedicalStoreManagement.Web/ViewModels/ProductViewModel.cs
using MedicalStoreManagement.Application.Helpers;
using MedicalStoreManagement.Application.Products;
using MedicalStoreManagement.Domain.Entities;
using MedicalStoreManagement.Web.ViewModels.Base;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MedicalStoreManagement.Web.ViewModels
{
    public class ProductViewModel : BaseViewModel
    {
        #region Properties
        public IList<Product> Products { get; set; }
        #endregion

        #region Input
        public int Id { get; set; }
        public string Product_Name { get; set; }
        public string Unit { get; set; }
        public string PricePerUnit { get; set; }
        public int FurnitorID { get; set; }
        public string CompanyName { get; set; }
        public int CategoryID { get; set; }
        public string Product_Description { get; set; }

        public IList<Furnitor> Furnitors { get; set; }

        public IList<Category> Categories { get; set; }
        #endregion

        #region Init
        public override void Init()
        {
            if (initialized) return;
            Products = HttpContextHelper.Context.RequestServices.GetRequiredService<IProductService>().GetProducts().Result;
            base.Init();
        }
        #endregion

        #region Load Data
        public void LoadData(int productId)
        {
            try
            {
                var product = Products.FirstOrDefault(x => x.Id == productId);
                Id = product.Id;
                Product_Name = product.Product_Name;
                Unit = product.Unit;
                PricePerUnit = product.PricePerUnit;
                FurnitorID = product.FurnitorID;
                CompanyName = product.CompanyName;
                CategoryID = product.CategoryID;
                Product_Description = product.Product_Description;
            }
            catch (Exception)
            {

                throw;
            }
        }
        #endregion
    }
}

001_src/MedicalStoreManagement/MedicalStoreManagement.Web/Controllers/BillingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MedicalStoreManagement.Web.Controllers
{
    public class BillingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

001_src/MedicalStoreManagement/MedicalStoreManagement.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MedicalStoreManagement.Application.Categories;
using MedicalStoreManagement.Application.Furnitors;
using MedicalStoreManagement.Application.Products;
using MedicalStoreManagement.Domain._DTO;
using MedicalStoreManagement.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace MedicalStoreManagement.Web.Controllers
{
    public class ProductController : Controller
    {
        #region Properties
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IFurnitorService _furnitorService;
        #endregion

        #region Constructor
        public ProductController(IProductService productService, ICategoryService categoryService, IFurnitorService furnitorService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _furnitorService = furnitorService;
        }
        #endregion

        #region View
        // GET: Product
        public IActionResult Index()
        {
            return View(new ProductViewModel());
        }

        public async Task<IActionResult> DeleteProduct(int productId)
        {
            await _productService.DeleteProduct(productId);

            return RedirectToAction("Index", "Product");
        }

        [HttpGet]
        public IActionResult AddProduct()
        {
            var model = new ProductViewModel();
            model.Categories = _categoryService.GetCategories().Result;
            model.Furnitors = _furnitorService.GetFurnitors().Result;
            return View(model);
        }

        public IActionResult Details(ProductViewModel model, int productId)
        {
            model.LoadData(productId);
            model.Categories = _categoryService.GetCategories().Result;
            model.Furnitors = _furnitorService.GetFurnitors().Result;
            return View(model);
        }

        public IActionResult EditProduct(ProductViewModel model, int productId)
        {
            model.LoadData(productId);
            model.Categories = _categoryService.GetCategories().Result;
            model.Furnitors = _furnitorService.GetFurnitors().Result;
            return View(model);
        }
        #endregion

        #region Add Product
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddProduct(ProductViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            await _productService.AddProduct(PrepareProductSubmissionModel(model));
            return RedirectToAction("Index", "Product");
            //return View(model);
        }
        #endregion

        #region Edit Product
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProduct(ProductViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            await _productService.UpdateProduct(PrepareProductUpdateSubmissionModel(model));
            return RedirectToAction("Index", "Product");
            //return View(model);
        }
        #endregion

        #region Private Methods
        private ProductSubmissionModel PrepareProductSubmissionModel(ProductViewModel model)
        {
            return new ProductSubmissionModel
            {
                Product_Name = model.Product_Name,
                Unit = model.Unit,
                PricePerUnit = model.PricePerUnit,
                FurnitorID = model.FurnitorID,
                CompanyName = model.CompanyName,
                CategoryID = model.CategoryID,
                Product_Description = model.Product_Description
            };
        }

        private ProductUpdateSubmissionModel PrepareProductUpdateSubmissionModel(ProductViewModel model)
        {
            return new ProductUpdateSubmissionModel
            {
                Id = model.Id,
                Product_Name = model.Product_Name,
                Unit = model.Unit,
                PricePerUnit = model.PricePerUnit,
                FurnitorID = model.FurnitorID,
                CompanyName = model.CompanyName,
                CategoryID = model.CategoryID,
                Product_Description = model.Product_Description
            };
        }
        #endregion
    }
}

001_src/MedicalStoreManagement/MedicalStoreManagement.Web/Views/Product/AddProduct.cshtml
@model MedicalStoreManagement.Web.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "AddProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 style="color: darkred">AddProduct</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddProduct">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Product_Name" class="control-label"></label>
                <input asp-for="Product_Name" placeholder="Enter product name" class="form-control" />
                <span asp-validation-for="Product_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Unit" class="control-label"></label>
                <input asp-for="Unit" placeholder="number mg (miligram)" class="form-control" />
                <span asp-validation-for="Unit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PricePerUnit" class="control-label"></label>
                <input asp-for="PricePerUnit" placeholder="Enter price per unit" class="form-control" />
                <span asp-validation-for="PricePerUnit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FurnitorID" class="control-label"></label>
                <select asp-for="FurnitorID" class="form-control">
                    <option value="#">Zgjedh furnitorin</option>

                    @foreach (var furnitor in Model.Furnitors)
                    {
                        <option value="@furnitor.Id">@furnitor.Furnitor_FirstName</option>
                    }
                </select>
                <span asp-validation-for="FurnitorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" placeholder="Enter company name" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryID" class="control-label"></label>
                <select asp-for="CategoryID" class="form-control">
                    <option value="#">Zgjedh kategorine</option>

                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.Id">@category.Category_Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Description" class="control-label"></label>
                <input asp-for="Product_Description" placeholder="Enter product description" class="form-control" />
                <span asp-validation-for="Product_Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add Product" class="btn btn-success" />
                <input type="reset" value="Clear" class="btn btn-danger"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

001_src/MedicalStoreManagement/MedicalStoreManagement.Web/Views/Product/Details.cshtml
@model MedicalStoreManagement.Web.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 style="color: darkred">Details</h1>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Product_Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Product_Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PricePerUnit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PricePerUnit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FurnitorID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FurnitorID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CategoryID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CategoryID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Product_Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Product_Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

001_src/MedicalStoreManagement/MedicalStoreManagement.Web/Views/Product/EditProduct.cshtml
@model MedicalStoreManagement.Web.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "EditProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditProduct</h2>

<h4>ProductViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditProduct">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Product_Name" class="control-label"></label>
                <input asp-for="Product_Name" class="form-control" />
                <span asp-validation-for="Product_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Unit" class="control-label"></label>
                <input asp-for="Unit" class="form-control" />
                <span asp-validation-for="Unit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PricePerUnit" class="control-label"></label>
                <input asp-for="PricePerUnit" class="form-control" />
                <span asp-validation-for="PricePerUnit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FurnitorID" class="control-label"></label>
                <select asp-for="FurnitorID" asp-items="@{new SelectList(Model.Furnitors, "Id", "Furnitor_FirstName")}" class="form-control">
                    <option value="">None</option>
                </select>
                <span asp-validation-for="FurnitorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryID" class="control-label"></label>
                <select asp-for="CategoryID" asp-items="@{new SelectList(Model.Categories, "Id", "Category_Name")}" class="form-control">
                    <option value="">None</option>
                </select>
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Description" class="control-label"></label>
                <input asp-for="Product_Description" placeholder="Enter product description" class="form-control" />
                <span asp-validation-for="Product_Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

001_src/MedicalStoreManagement/MedicalStoreManagement.Web/Views/Product/Index.cshtml
@model MedicalStoreManagement.Web.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 style="color: darkred">Index</h1>

<p>
    <a asp-action="AddProduct">Create New Product</a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Unit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PricePerUnit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FurnitorID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product_Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Products) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                <a asp-area="" asp-controller="Billing" asp-action="Index">@Html.DisplayFor(modelItem => item.Product_Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Unit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PricePerUnit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Furnitor.Furnitor_FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Category_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product_Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditProduct", new { productId = item.Id }) |
                @Html.ActionLink("Details", "Details", new { productId = item.Id }) |
                @Html.ActionLink("Delete", "DeleteProduct", new { productId = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>